version: '3'
services:
  puppet:
    build:
      context: .
      dockerfile: Dockerfile.puppet
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver-standalone-conjur
    volumes:
      - ./puppet/manifests:/etc/puppetlabs/code/environments/production/manifests
    extra_hosts:
      - "{{ CONJUR_DNS_NAME }}:{{ CONJUR_IP }}"
  agent:
    image: puppet/puppet-agent-ubuntu
    depends_on: [  puppet ]
    volumes:
      - ./tmp:/tmp
    extra_hosts:
      - "{{ CONJUR_DNS_NAME }}:{{ CONJUR_IP }}"
