version: '3'
services:
  puppet:
    build:
      context: .
      dockerfile: Dockerfile.puppet
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver-standalone-conjur
    volumes:
      - ./puppet/manifests:/etc/puppetlabs/code/environments/production/manifests
    extra_hosts:
      - "{{ CONJUR_DNS_NAME }}:{{ CONJUR_IP }}"
  agent:
    image: puppet/puppet-agent-ubuntu
    depends_on: [  puppet ]
    volumes:
      - ./tmp:/tmp
    extra_hosts:
      - "{{ CONJUR_DNS_NAME }}:{{ CONJUR_IP }}"
  conjur-cli:
    container_name: conjur-cli
    image: cyberark/conjur-cli:4
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: https://{{ CONJUR_DNS_NAME }}/api
      CONJUR_ACCOUNT: {{ CONJUR_ACCOUNT }}
      CONJUR_AUTHN_LOGIN: {{ CONJUR_AUTHN_LOGIN }}
      CONJUR_URL: https://{{ CONJUR_DNS_NAME }}
    volumes:
      - ./conjur:/demo
    extra_hosts:
      - "{{ CONJUR_DNS_NAME }}:{{ CONJUR_IP }}"
